### ISSUE TITLE
Cannot initialize ARD object

### ISSUE THREAD

**Issue by hzhou-nmdp** [nmdp-bioinformatics/py-ard#23] opened 2019-07-10 21:46 UTC
After I `pip install pyard`, I have tried both 
```python
ard = ARD()
```
and 
```python
ard = ARD('3290')
```
Both gave me this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hzhou/git/pyARD/pyard/pyard.py", line 131, in __init__
    urllib.request.urlretrieve(ars_url, ars_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```
Then when I try to install from sauce, it gives me huge amount of error  message. And the last one is shown here.
```
Command "/Users/hzhou/git/pyARD/venv/bin/python3 /Users/hzhou/git/pyARD/venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/lr/ck2pm9ws4s98mtzbs_4lmbpm0000gp/T/pip-build-env-79s2ysoq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython "numpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; python_version=='3.6'" "numpy==1.13.1; python_version>='3.7'"" failed with error code 1 in None
```
I am using Python 3.7.3 by the way

**Comment by mmaiers-nmdp** [comment] 2019-08-06 03:10
@pbashyal-nmdp can you look at this issue? I can't reproduce the error.  I'm using Python 3.7.2.

**Comment by pbashyal-nmdp** [comment] 2019-08-06 17:11
@hzhou-nmdp Are you using conda ? It seems to have problem with `certifi`. Try upgrading it.

The following works for me:
```
conda create --name pyard_test
conda activate pyard_test
pip install --upgrade --ignore-installed certifi
pip install pyard
```
Then using pyARD
```
$ python3
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyard import ARD
>>> ard = ARD('3290')
>>> allele = "A*01:01:01"
>>> ard.redux(allele, 'G')
'A*01:01:01G'
>>> ard = ARD()
>>> ard.redux(allele, 'G')
'A*01:01:01G'
>>>
```

**Comment by hzhou-nmdp** [comment] 2019-08-06 18:09
Hi Pradeep,

Thank you. I think you mean using the “pip” under the pyard_test environment, so we need to conda install “pip” first. However for some reason, after installation, the system still couldn’t find the installed “pip”, so I went to the specific folder to execute that “pip”. This does solve the issue. I wonder why the original “pip” didn’t work.


conda create --name pyard_test

conda activate pyard_test

conda install pip

cd /Users/hzhou/miniconda3/envs/pyard_test/bin/

./pip install --upgrade --ignore-installed certifi

./pip install pyard

Best,

Huajun

**Comment by pbashyal-nmdp** [comment] 2020-04-16 14:06
Closing. Not an issue  anymore.

**Closed by pbashyal-nmdp** 2020-04-16 14:06 UTC
